### ISSUE TITLE
adts play intermitted crashes

### ISSUE THREAD

**Issue by cybernard** [theori-io/nrsc5#128] opened 2017-12-22 05:25 UTC
nrsc5  106.1  0 -o sample.adts -f adts

Is recording just find and then this error and it dies,

nrsc5: /src/hdradio/nrsc5/src/bitreader.h:26: br_read1bit: Assertion `br->buf != br->end' failed.

**Comment by argilo** [comment] 2017-12-22 12:54
Duplicate of #53.

**Closed by argilo** 2017-12-22 12:54 UTC
