### ISSUE TITLE
Q doesn't quit application on Windows. Audio just stops

### ISSUE THREAD

**Issue by pclov3r** [theori-io/nrsc5#202] opened 2019-03-10 14:25 UTC
So it seems with https://github.com/theori-io/nrsc5/pull/197 pushing Q on windows doesn't quit the program. It just stops the audio.

**Comment by awesie** [comment] 2019-03-13 07:07
After a quick look, I think this is a bug in librtlsdr or libusb. The problem is that when we cancel the async transfer (using `rtlsdr_cancel_async`) the return value of `rtlsdr_read_async` will be -5 on Windows, indicating an error, instead of 0 on *nix.

I'm going to commit a fix for the symptom (since it should be fixed in any case) but I may want to further investigate the root cause later.

**Closed** 2019-03-13 07:09 UTC
Labels: bug
